name: Helloworld 
#  Here ON means when to trigger this pipeline we can tigger on push or some manula events like ( creating PR, updating PR, creating branches )
on: [pull]  #this is like triggers 
jobs: #pipeline , one workflow have multiple pipelines 
  hello:
     runs-on: ubuntu-latest
     steps: #stages 
       - name: step1 
         run: echo "hello world"
       - name: step2
         run: echo "hello Github Actions"



