name: MyFristGithubWorkFlow  # workflow name
on: [push] # when this workflow shoud run
jobs: # Pipeline
  vinodh: # job name
    runs-on: ubuntu-latest # like os where this workflow should run
    steps: #  like stages 
      - name: step1 
        if: github.ref == 'refs/heads/feature-**'
        run: echo "hello vinodh"
      - name: step2
        if: github.ref == 'refs/heads/feature-**'
        run: echo "Welcome to Github Actions vinodh"
      - name: step3
        if: github.ref == 'refs/heads/feature-**'
        run: echo "This second workflow"
