name: 3-Tier-Application-deployment
on: [push,pull]
jobs: 
  3-Tier-Application:  #job name
    runs-on: ubuntu-latest
    steps:
      - name: Code Check-out
        run: echo "code check-out form Github-Done-Sucessfully"
      - name: Code quality checks
        run: echo "Code quality check done: By Sonar Qube Scanner"
      - name: Build 
        run: echo "Code build done: By Maven"
      - name: Docker Image
        run: echo "Creating a Docekr Image"
      - name: Image Push 
        run: echo "Image pushed to ECR repo"
      
    
