name: Conditions
on: [push]
jobs:
  ConditionsWhenThisJobRun:
    runs-on: ubuntu-latest
    steps:
      - name: if Devopler pushed the changes to Feature branch then its Should trigger
        if: github.ref == 'refs/heads/feature-**'
        run: echo "feature Branch is Running"
      - name: if Devopler pushed the changes to Main branch then its Should trigger
        if: github.ref == 'refs/heads/main'
        run: echo "main Branch is Running"
   
   